# Generated by Django 4.2.16 on 2024-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(max_length=255, upload_to='%Y%m/slider', verbose_name='图片地址'),
        ),
    ]
